name: NWChem website update
on:
  release:
  schedule:
    - cron: '0 0 * * *'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  build-deploy:
    name: Build and deploy docs

    runs-on: ubuntu-latest

    steps:
      - name: Checkout nwchem code
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          pwd
          ls -lart
          cd ..
          ls -lart
          git clone  --depth 1  --filter=blob:none --sparse \
          https://github.com/nwchemgit/nwchem nwchem
          cd nwchem
          git sparse-checkout set contrib/mkdocs
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 1
      - name: check nwchem/contrib/mkdocs
        shell: bash
        run: |
          ls -lrta
          ls -larta nwchem
          ls -Rlarta nwchem
      - name: Set up Python 3
        uses: actions/setup-python@v2
      
      - name: install mkdocs and plugins
        shell: bash
        working-directory: contrib/mkdocs
        run: |
          pwd
          bash ./install_mkdocs.sh
          mkdocs -h || true
      - name: checkout wiki
        uses: actions/checkout@v2
        with:
          path: contrib/mkdocs/docs
          repository: nwchemgit/nwchem-wiki
          persist-credentials: false
          fetch-depth: 1
      - name: check wiki source
        shell: bash
        working-directory: contrib/mkdocs
        run: |
          ls -lrt docs
      - name: checkout archived forum
        uses: actions/checkout@v2
        with:
          path: contrib/mkdocs/docs/archivedforum
          repository: nwchemgit/archivedforum
          persist-credentials: false
          fetch-depth: 1
      - name: check archiveforum source
        shell: bash
        working-directory: contrib/mkdocs/docs/
        run: |
          ls -lrt archivedforum
          mv archivedforum/Special_AWCforum .
      - name: build website
        shell: bash
        working-directory: contrib/mkdocs
        run: |
          MKDOCS_SERVE=B bash ./build_website.sh
          ls -lart || true
          ls -lart site/index.html || true
      - name: checkout website
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPOSITORY_TOKEN }}
          path: contrib/mkdocs/nwchemgit.github.io
          repository: nwchemgit/nwchemgit.github.io
      - name: update nwchemgit.github.io with new content
        shell: bash
        working-directory: contrib/mkdocs
        run: |
          rsync --exclude=.git -a site/* nwchemgit.github.io/.
          ls -lart site/index.html || true
          ls -lart nwchemgit.github.io/index.html || true
          cd nwchemgit.github.io
          git diff --stat
          git log -1
      - name: Commit changes
        shell: bash
        working-directory: contrib/mkdocs/nwchemgit.github.io
        run: |
            git config user.name "nwchemgit"
            git config user.email "nwchemgit@gmail.com"
            git commit -m website\ changes\ on\ `date +%a_%b_%d_%H:%M:%S_%Y` -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          directory: contrib/mkdocs/nwchemgit.github.io
          github_token: ${{ secrets.REPOSITORY_TOKEN }}
          branch: ${{ github.ref }}
          repository: nwchemgit/nwchemgit.github.io
      - name: Check commit result
        shell: bash
        working-directory: contrib/mkdocs/nwchemgit.github.io
        run: |
            git log -2
